from PyQt5 import QtCore, QtGui, QtWidgets

from utils import prefix_converter


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1070, 597)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 400, 501, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.Rc = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Rc.sizePolicy().hasHeightForWidth())
        self.Rc.setSizePolicy(sizePolicy)
        self.Rc.setMinimumSize(QtCore.QSize(0, 30))
        self.Rc.setObjectName("Rc")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Rc)
        self.Rb = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Rb.sizePolicy().hasHeightForWidth())
        self.Rb.setSizePolicy(sizePolicy)
        self.Rb.setMinimumSize(QtCore.QSize(0, 30))
        self.Rb.setObjectName("Rb")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Rb)
        self.Re = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Re.sizePolicy().hasHeightForWidth())
        self.Re.setSizePolicy(sizePolicy)
        self.Re.setMinimumSize(QtCore.QSize(0, 30))
        self.Re.setObjectName("Re")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Re)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 511, 261))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.Ein = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ein.sizePolicy().hasHeightForWidth())
        self.Ein.setSizePolicy(sizePolicy)
        self.Ein.setMinimumSize(QtCore.QSize(0, 30))
        self.Ein.setObjectName("Ein")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Ein)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.Ic = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ic.sizePolicy().hasHeightForWidth())
        self.Ic.setSizePolicy(sizePolicy)
        self.Ic.setMinimumSize(QtCore.QSize(0, 30))
        self.Ic.setObjectName("Ic")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Ic)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.Ube = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ube.sizePolicy().hasHeightForWidth())
        self.Ube.setSizePolicy(sizePolicy)
        self.Ube.setMinimumSize(QtCore.QSize(0, 30))
        self.Ube.setObjectName("Ube")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Ube)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.hfe = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hfe.sizePolicy().hasHeightForWidth())
        self.hfe.setSizePolicy(sizePolicy)
        self.hfe.setMinimumSize(QtCore.QSize(0, 30))
        self.hfe.setObjectName("hfe")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.hfe)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setMinimumSize(QtCore.QSize(0, 82))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        self.Ue = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ue.sizePolicy().hasHeightForWidth())
        self.Ue.setSizePolicy(sizePolicy)
        self.Ue.setMinimumSize(QtCore.QSize(0, 75))
        self.Ue.setObjectName("Ue")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Ue)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(540, 80, 511, 451))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../img/boosters/a_class_2.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(380, 30, 47, 13))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")

        self.Ein.setValidator(QtGui.QDoubleValidator())
        self.Ic.setValidator(QtGui.QDoubleValidator())
        self.Ube.setValidator(QtGui.QDoubleValidator())
        self.hfe.setValidator(QtGui.QDoubleValidator())
        self.Rc.setValidator(QtGui.QDoubleValidator())
        self.Rb.setValidator(QtGui.QDoubleValidator())
        self.Ue.setValidator(QtGui.QDoubleValidator())
        self.Re.setValidator(QtGui.QDoubleValidator())

        self.pushButton.clicked.connect(self.calculate)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Сопротивление базового резистора Rб, Ом"))
        self.label_4.setText(_translate("Form", "Сопротивление коллекторного резистора Rк, Ом"))
        self.label_10.setText(_translate("Form", "Сопротивление эмиттерного резистора Re, Ом"))
        self.label.setText(_translate("Form", "Напряжения истоника питания E, В"))
        self.label_2.setText(_translate("Form", "Ток коллектора Iк, А"))
        self.label_3.setText(_translate("Form", "Переход База-Эмиттер Uбэ, В"))
        self.label_8.setText(_translate("Form", "Коэффициент усиления по току(h21э)"))
        self.label_9.setText(_translate("Form", "Часть напряжение на резисторе Rэ \n"
"от источника питания обычно, \n"
"выбирают от (0,1 до 0,3)  "))
        self.pushButton.setText(_translate("Form", "Расчитать"))

    def calculate(self):
        Ein = float(self.Ein.text().replace(',', '.'))
        Ic = float(self.Ic.text().replace(',', '.'))
        Ube = float(self.Ube.text().replace(',', '.'))
        hfe = float(self.hfe.text().replace(',', '.'))
        Ue_koef = float(self.Ue.text().replace(',', '.'))
        Ue = Ue_koef * Ein
        Uce = (Ein - Ue) / 2
        Rk = Uce/Ic
        Ib = Ic/hfe
        Rb = (Uce - Ube)/Ib
        Re = Ue/(Ic+Ib)
        self.Rb.setText(prefix_converter(Rb).replace(',','.'))
        self.Rc.setText(prefix_converter(Rk).replace(',','.'))
        self.Re.setText(prefix_converter(Re).replace(',','.'))
