from PyQt5 import QtCore, QtGui, QtWidgets

from utils import prefix_converter

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1070, 597)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 310, 491, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.Rc = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Rc.sizePolicy().hasHeightForWidth())
        self.Rc.setSizePolicy(sizePolicy)
        self.Rc.setMinimumSize(QtCore.QSize(0, 30))
        self.Rc.setObjectName("Rc")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Rc)
        self.Rb = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Rb.setMinimumSize(QtCore.QSize(0, 30))
        self.Rb.setObjectName("Rb")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Rb)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(30, 92, 478, 173))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.Ein = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.Ein.setMinimumSize(QtCore.QSize(0, 30))
        self.Ein.setObjectName("Ein")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Ein)
        self.Ic = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.Ic.setMinimumSize(QtCore.QSize(0, 30))
        self.Ic.setObjectName("Ic")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Ic)
        self.Ube = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.Ube.setMinimumSize(QtCore.QSize(0, 30))
        self.Ube.setObjectName("Ube")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Ube)
        self.hfe = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hfe.sizePolicy().hasHeightForWidth())
        self.hfe.setSizePolicy(sizePolicy)
        self.hfe.setMinimumSize(QtCore.QSize(0, 30))
        self.hfe.setObjectName("hfe")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.hfe)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(540, 80, 511, 451))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../img/boosters/a_class_1.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(380, 30, 47, 13))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")

        self.Ein.setValidator(QtGui.QDoubleValidator())
        self.Ic.setValidator(QtGui.QDoubleValidator())
        self.Ube.setValidator(QtGui.QDoubleValidator())
        self.hfe.setValidator(QtGui.QDoubleValidator())
        self.Rc.setValidator(QtGui.QDoubleValidator())
        self.Rb.setValidator(QtGui.QDoubleValidator())

        self.pushButton.clicked.connect(self.calculate)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Сопротивление коллекторного резистора, Ом"))
        self.label_5.setText(_translate("Form", "Сопротивление базового резистора, Ом"))
        self.label.setText(_translate("Form", "Напряжения истоника питания, В"))
        self.label_2.setText(_translate("Form", "Ток коллектора, А"))
        self.label_3.setText(_translate("Form", "Переход База-Эмиттер, В"))
        self.pushButton.setText(_translate("Form", "Расчитать"))
        self.label_8.setText(_translate("Form", "Коэффициент усиления (h21э)"))

    def calculate(self):
        Ein = float(self.Ein.text().replace(',', '.'))
        Ic = float(self.Ic.text().replace(',', '.'))
        Ube = float(self.Ube.text().replace(',', '.'))
        hfe = float(self.hfe.text().replace(',', '.'))
        Rk = Ein/(2*Ic)
        Ib = Ic/hfe
        Uc = Ein - Ic * Rk
        Rb = (Uc - Ube)/Ib
        self.Rb.setText(prefix_converter(Rb).replace(',','.'))
        self.Rc.setText(prefix_converter(Rk).replace(',','.'))
