from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1032, 727)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bossters = QtWidgets.QComboBox(self.layoutWidget)
        self.bossters.setEnabled(True)
        self.bossters.setObjectName("bossters")
        self.bossters.addItem("")
        self.bossters.addItem("")
        self.bossters.addItem("")
        self.horizontalLayout.addWidget(self.bossters)
        self.RLC = QtWidgets.QComboBox(self.layoutWidget)
        self.RLC.setObjectName("RLC")
        self.RLC.addItem("")
        self.RLC.addItem("")
        self.RLC.addItem("")
        self.horizontalLayout.addWidget(self.RLC)
        self.converters = QtWidgets.QComboBox(self.layoutWidget)
        self.converters.setObjectName("converters")
        self.converters.addItem("")
        self.converters.addItem("")
        self.horizontalLayout.addWidget(self.converters)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_4)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bossters.setItemText(0, _translate("MainWindow", "Усилители"))
        self.bossters.setItemText(1, _translate("MainWindow", "А-класс"))
        self.bossters.setItemText(2, _translate("MainWindow", "А_класс ОЭ 1"))
        self.RLC.setItemText(0, _translate("MainWindow", "RLC контура"))
        self.RLC.setItemText(1, _translate("MainWindow", "RL"))
        self.RLC.setItemText(2, _translate("MainWindow", "RC"))
        self.converters.setItemText(0, _translate("MainWindow", "Понижающий"))
        self.converters.setItemText(1, _translate("MainWindow", "Повышающий"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Что-то ещё 2"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
