# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 736)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 534, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bossters = QtWidgets.QComboBox(self.layoutWidget)
        self.bossters.setEnabled(True)
        self.bossters.setObjectName("bossters")
        self.bossters.addItem("")
        self.bossters.addItem("")
        self.bossters.addItem("")
        self.horizontalLayout.addWidget(self.bossters)
        self.filters = QtWidgets.QComboBox(self.layoutWidget)
        self.filters.setObjectName("filters")
        self.filters.addItem("")
        self.filters.addItem("")
        self.filters.addItem("")
        self.filters.addItem("")
        self.filters.addItem("")
        self.filters.addItem("")
        self.horizontalLayout.addWidget(self.filters)
        self.rlc = QtWidgets.QComboBox(self.layoutWidget)
        self.rlc.setObjectName("rlc")
        self.rlc.addItem("")
        self.rlc.addItem("")
        self.rlc.addItem("")
        self.horizontalLayout.addWidget(self.rlc)
        self.opetaionals = QtWidgets.QComboBox(self.layoutWidget)
        self.opetaionals.setObjectName("opetaionals")
        self.opetaionals.addItem("")
        self.opetaionals.addItem("")
        self.opetaionals.addItem("")
        self.horizontalLayout.addWidget(self.opetaionals)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bossters.setItemText(0, _translate("MainWindow", "Усилители"))
        self.bossters.setItemText(1, _translate("MainWindow", "А_класс ОЭ 1"))
        self.bossters.setItemText(2, _translate("MainWindow", "А_класс ОЭ 2"))
        self.filters.setItemText(0, _translate("MainWindow", "Фильтры"))
        self.filters.setItemText(1, _translate("MainWindow", "ФНЧ"))
        self.filters.setItemText(2, _translate("MainWindow", "ФВЧ"))
        self.filters.setItemText(3, _translate("MainWindow", "Полосовой фильтр"))
        self.filters.setItemText(4, _translate("MainWindow", "Активный ФНЧ"))
        self.filters.setItemText(5, _translate("MainWindow", "Активный ФВЧ"))
        self.rlc.setItemText(0, _translate("MainWindow", "RLC"))
        self.rlc.setItemText(1, _translate("MainWindow", "Последовательный RLC"))
        self.rlc.setItemText(2, _translate("MainWindow", "Параллельный RLC"))
        self.opetaionals.setItemText(0, _translate("MainWindow", "Операционые усилители"))
        self.opetaionals.setItemText(1, _translate("MainWindow", "Инверт включение"))
        self.opetaionals.setItemText(2, _translate("MainWindow", "Неинверт включение"))
