from PyQt5 import QtCore, QtGui, QtWidgets

from utils import prefix_converter

from math import pi, atan


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1070, 597)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 370, 501, 151))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.Eout = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Eout.sizePolicy().hasHeightForWidth())
        self.Eout.setSizePolicy(sizePolicy)
        self.Eout.setMinimumSize(QtCore.QSize(0, 30))
        self.Eout.setObjectName("Eout")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Eout)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.Freq = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Freq.sizePolicy().hasHeightForWidth())
        self.Freq.setSizePolicy(sizePolicy)
        self.Freq.setMinimumSize(QtCore.QSize(0, 30))
        self.Freq.setObjectName("Freq")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Freq)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.Phase = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Phase.sizePolicy().hasHeightForWidth())
        self.Phase.setSizePolicy(sizePolicy)
        self.Phase.setMinimumSize(QtCore.QSize(0, 30))
        self.Phase.setObjectName("Phase")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Phase)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 511, 173))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.RR = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RR.sizePolicy().hasHeightForWidth())
        self.RR.setSizePolicy(sizePolicy)
        self.RR.setMinimumSize(QtCore.QSize(0, 30))
        self.RR.setObjectName("RR")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.RR)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.CC = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CC.sizePolicy().hasHeightForWidth())
        self.CC.setSizePolicy(sizePolicy)
        self.CC.setMinimumSize(QtCore.QSize(0, 30))
        self.CC.setObjectName("CC")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.CC)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.Ein = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ein.sizePolicy().hasHeightForWidth())
        self.Ein.setSizePolicy(sizePolicy)
        self.Ein.setMinimumSize(QtCore.QSize(0, 30))
        self.Ein.setObjectName("Ein")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Ein)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.Freq_in = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Freq_in.sizePolicy().hasHeightForWidth())
        self.Freq_in.setSizePolicy(sizePolicy)
        self.Freq_in.setMinimumSize(QtCore.QSize(0, 30))
        self.Freq_in.setObjectName("Freq_in")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Freq_in)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(540, 80, 511, 451))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../img/filters/LPF.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(380, 30, 47, 13))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")

        self.RR.setValidator(QtGui.QDoubleValidator())
        self.CC.setValidator(QtGui.QDoubleValidator())
        self.Ein.setValidator(QtGui.QDoubleValidator())
        self.Eout.setValidator(QtGui.QDoubleValidator())
        self.Phase.setValidator(QtGui.QDoubleValidator())
        self.Freq.setValidator(QtGui.QDoubleValidator())
        self.Freq_in.setValidator(QtGui.QDoubleValidator())

        self.pushButton.clicked.connect(self.calculate)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Выходное напряжение, В"))
        self.label_5.setText(_translate("Form", "Частота среза, Гц"))
        self.label_10.setText(_translate("Form", "Сдвиг фазы, граудсы"))
        self.label.setText(_translate("Form", "Сопроивление резистора R, Ом"))
        self.label_3.setText(_translate("Form", "Емкость C, мкФ"))
        self.pushButton.setText(_translate("Form", "Расчитать"))
        self.label_8.setText(_translate("Form", "Входное напряжение, В"))
        self.label_9.setText(_translate("Form", "Входная частота, Гц"))

    def calculate(self):
        RR = float(self.RR.text().replace(',', '.'))
        CC = float(self.CC.text().replace(',', '.')) * 1e-6
        Ein = float(self.Ein.text().replace(',', '.'))
        Freq_in = float(self.Freq_in.text().replace(',', '.'))

        Xc = (2 * pi * Freq_in * CC) ** -1
        Eout = Ein * Xc / (RR*RR + CC*CC)**0.5
        fc = (2 * pi * RR * CC) ** -1
        Phase = - atan(2 * pi * Freq_in * RR * CC)
        self.Eout.setText(prefix_converter(Eout).replace(',','.'))
        self.Freq.setText(prefix_converter(fc).replace(',','.'))
        self.Phase.setText(prefix_converter(Phase).replace(',','.'))
