from PyQt5 import QtCore, QtGui, QtWidgets

from utils import prefix_converter

from math import pi, atan


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1070, 597)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 370, 501, 151))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.R1 = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R1.sizePolicy().hasHeightForWidth())
        self.R1.setSizePolicy(sizePolicy)
        self.R1.setMinimumSize(QtCore.QSize(0, 30))
        self.R1.setObjectName("R1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.R1)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.R2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R2.sizePolicy().hasHeightForWidth())
        self.R2.setSizePolicy(sizePolicy)
        self.R2.setMinimumSize(QtCore.QSize(0, 30))
        self.R2.setObjectName("R2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.R2)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.F_center = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F_center.sizePolicy().hasHeightForWidth())
        self.F_center.setSizePolicy(sizePolicy)
        self.F_center.setMinimumSize(QtCore.QSize(0, 30))
        self.F_center.setObjectName("F_center")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.F_center)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 511, 173))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.C1 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C1.sizePolicy().hasHeightForWidth())
        self.C1.setSizePolicy(sizePolicy)
        self.C1.setMinimumSize(QtCore.QSize(0, 30))
        self.C1.setObjectName("C1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.C1)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.C2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C2.sizePolicy().hasHeightForWidth())
        self.C2.setSizePolicy(sizePolicy)
        self.C2.setMinimumSize(QtCore.QSize(0, 30))
        self.C2.setObjectName("C2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.C2)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.pushButton)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.F_min = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F_min.sizePolicy().hasHeightForWidth())
        self.F_min.setSizePolicy(sizePolicy)
        self.F_min.setMinimumSize(QtCore.QSize(0, 30))
        self.F_min.setObjectName("F_min")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.F_min)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.F_max = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F_max.sizePolicy().hasHeightForWidth())
        self.F_max.setSizePolicy(sizePolicy)
        self.F_max.setMinimumSize(QtCore.QSize(0, 30))
        self.F_max.setObjectName("F_max")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.F_max)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(540, 80, 511, 451))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../img/filters/PBPF.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(380, 30, 47, 13))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")

        self.C1.setValidator(QtGui.QDoubleValidator())
        self.C2.setValidator(QtGui.QDoubleValidator())
        self.F_min.setValidator(QtGui.QDoubleValidator())
        self.F_max.setValidator(QtGui.QDoubleValidator())
        self.R1.setValidator(QtGui.QDoubleValidator())
        self.R2.setValidator(QtGui.QDoubleValidator())
        self.F_center.setValidator(QtGui.QDoubleValidator())

        self.pushButton.clicked.connect(self.calculate)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Сопротивлеление резистора R1, Ом"))
        self.label_5.setText(_translate("Form", "Сопротивлеление резистора R2, Ом"))
        self.label_10.setText(_translate("Form", "Центральная резонансная частота, Гц"))
        self.label.setText(_translate("Form", "Емкость C1, мкФ"))
        self.label_3.setText(_translate("Form", "Емкость C2, мкФ"))
        self.pushButton.setText(_translate("Form", "Расчитать"))
        self.label_8.setText(_translate("Form", "Минимальная частота, Гц"))
        self.label_9.setText(_translate("Form", "Максимальная частота, Гц"))

    def calculate(self):
        C1 = float(self.C1.text().replace(',', '.')) * 1e-6
        C2 = float(self.C2.text().replace(',', '.')) * 1e-6
        F_min = float(self.F_min.text().replace(',', '.'))
        F_max = float(self.F_max.text().replace(',', '.'))

        R1 = (2 * pi * F_min * C1) ** -1
        R2 = (2 * pi * F_max * C2) ** -1
        F_center = (F_min * F_max) ** 0.5
        self.R1.setText(prefix_converter(R1).replace(',','.'))
        self.R2.setText(prefix_converter(R2).replace(',','.'))
        self.F_center.setText(prefix_converter(F_center).replace(',','.'))